services:
  - type: web
    name: redsta
    env: python
    plan: free
    buildCommand: ./build.sh 
    startCommand: ./venv/bin/gunicorn app:app
    envVars:
      - key: REDDIT_CLIENT_ID
        value: x0-s9IIq4QznA0UxhdjK2w
      - key: REDDIT_CLIENT_SECRET
        value: lz3V0wcKvIlr1m0fxmhvNzhZKrQvmg
    autoDeploy: true
    region: oregon
    branch: main

